In [1]:
import cv2
import glob
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.svm import LinearSVC as svm
from sklearn.model_selection import train_test_split
import pickle
from sklearn import svm
from sklearn.svm import SVC
training_data=[]
for infile in glob.glob('Dataset\\*\\*'):
    a=cv2.imread(infile)
    gray=cv2.cvtColor(a,cv2.COLOR_BGR2GRAY)
    training_data.append(cv2.resize(gray,(350,350)).flatten())
training_data=np.asarray(training_data)

#x=training_data[0]
#plt.imshow(x.reshape(350,350))

testing_data=[]
for infile in glob.glob('Dataset//*//*'):
    path=infile.split('\\')
    #print(path[1])
    #testing_data.append(cv2.resize(gray,(350,350)).flatten())
    testing_data.append(path[1])
testing_data=np.asarray(testing_data)

X_train, X_test, y_train, y_test = train_test_split(training_data, testing_data,test_size=0.3)

SVM Training

In [2]:
#SVM=svm()
SVM=svm.SVC(kernel='rbf')
SVM.fit(X_train, y_train)

print ("Accuracy on training set:")
print (SVM.score(X_train, y_train))

print ("Accuracy on testing set:")
print (SVM.score(X_test, y_test))
   
y_pred = SVM.predict(X_test)
    
print ("Classification Report:")
print (metrics.classification_report(y_test, y_pred))

#print ("Confusion Matrix:")
#print (metrics.confusion_matrix(y_test, y_pred))
pickle.dump(SVM,open("model",'wb'))

Accuracy on training set:
0.9964285714285714
Accuracy on testing set:
0.8760330578512396
Classification Report:
              precision    recall  f1-score   support

        Alex       1.00      1.00      1.00        11
      Ananya       0.90      0.64      0.75        14
       Dhruv       0.93      1.00      0.96        13
       Ethan       1.00      1.00      1.00        13
     Kavisha       1.00      0.82      0.90        11
      Mithun       0.90      0.69      0.78        13
      Premal       1.00      0.92      0.96        12
       Sahil       0.71      0.83      0.77        12
        Sonu       0.43      0.86      0.57         7
         Tom       1.00      1.00      1.00        15

    accuracy                           0.88       121
   macro avg       0.89      0.88      0.87       121
weighted avg       0.91      0.88      0.88       121



In [3]:
#from sklearn.model_selection import cross_val_score
#scores = cross_val_score(SVM, X_train, y_train, cv=3)
#print(scores)

KNN Training 

In [4]:
KNN=knn(n_neighbors=3,leaf_size=4,p=1)
KNN.fit(X_train, y_train)

print ("Accuracy on training set:")
print (KNN.score(X_train, y_train))

print ("Accuracy on testing set:")
print (KNN.score(X_test, y_test))
   
y_pred = KNN.predict(X_test)
    
print ("Classification Report:")
print (metrics.classification_report(y_test, y_pred))

print ("Confusion Matrix:")
print (metrics.confusion_matrix(y_test, y_pred))
pickle.dump(KNN,open("model",'wb'))

Accuracy on training set:
0.9678571428571429
Accuracy on testing set:
0.8925619834710744
Classification Report:
              precision    recall  f1-score   support

        Alex       1.00      1.00      1.00        11
      Ananya       0.92      0.79      0.85        14
       Dhruv       0.93      1.00      0.96        13
       Ethan       1.00      1.00      1.00        13
     Kavisha       0.75      0.82      0.78        11
      Mithun       0.85      0.85      0.85        13
      Premal       1.00      0.83      0.91        12
       Sahil       0.92      0.92      0.92        12
        Sonu       0.44      0.57      0.50         7
         Tom       1.00      1.00      1.00        15

    accuracy                           0.89       121
   macro avg       0.88      0.88      0.88       121
weighted avg       0.90      0.89      0.90       121

Confusion Matrix:
[[11  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  3  0]
 [ 0  0 13  0  0  0  0  0  0  0]
 [ 0  0  0 1

In [ ]:
#from sklearn.model_selection import cross_val_score
#scores = cross_val_score(KNN, X_train, y_train, cv=3)
#print(scores)